name: expense_management
description: Ứng dụng quản lý tài chính cá nhân với SQLite cho Mobile & Desktop.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.8+4
  path: ^1.8.3
  intl: ^0.19.0
  provider: ^6.1.0
  shared_preferences: ^2.2.0
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
